### ISSUE TITLE
Can't resolve 'styled-jsx/css' 

### ISSUE THREAD

**Issue by markbrouch** [coox/styled-jsx-css-loader#3]
I have a brand new Next.js project set up (v4.1.4) with `styled-jsx-css-loader` configured in `next.config.js` exactly as it says in the README here and am trying to import a css file on `index.js`:

```js
import styles from '../styles/styles.css';

export default () => (
  <div>
    <style jsx>{styles}</style>
  </div>
);
```

However, getting the following error upon starting next:
```
Error in styles/styles.css
Module not found: Error: Can't resolve 'styled-jsx/css' in '...'
```
and the console error:
```
 ERROR  Failed to compile with 1 errors

This dependency was not found:

* styled-jsx/css in ./styles/styles.css

To install it, you can run: npm install --save styled-jsx/css
```

What am I doing wrong?

**Comment by coox** [comment]
Oh, didn’t realise that merging #4 would automatically close this issue.

@markbrouch, please feel free to re-open if updated instructions do not resolve your problem.

**Comment by markbrouch** [comment]
Awesome, thanks @coox!

I was able to use this to get modular styles working with Semantic UI quite simply:
```jsx
import {Button} from 'semantic-ui-react'

import buttonStyle from 'semantic-ui-css/components/button.css'

export default () => (
	<div>
		<Button primary>Test</Button>
		<style jsx global>
			{buttonStyle}
		</style>
	</div>
)
```

This reduced the app.js bundle size in prod from 2.0MB for using the entire semantic-ui-css stylesheet to just 638kb, huge savings!!
