### ISSUE TITLE
Flash Of Unstyled Content

### ISSUE THREAD

**Issue by tom2strobl** [coox/styled-jsx-css-loader#5]
Hi there,

I'm using `styled-jsx-css-loader` on the next.js stack exactly as you suggested in the README, but I'm getting a FOUC when loading a page which is fairly annoying:

![gif](http://files.wild.as/KBbLPL/22YT7B5U+)

The code – shortened to what's relevant (the sass plugin doesnt make a difference):

```javascript
// .babelrc
{
  "presets": [
    [
      "next/babel",
      {
        "preset-env": { "modules": "commonjs" },
        "styled-jsx": {
          "plugins": [
            "styled-jsx-plugin-sass"
          ]
        }
      }
    ]
  ]
}

// next.config.js
[...]
{
      test: /\.css/,
      use: [
        {
          loader: 'emit-file-loader',
          options: {
            name: 'dist/[path][name].[ext].js',
          },
        },
        {
          loader: 'babel-loader',
          options: {
            babelrc: false,
            extends: path.resolve(__dirname, './.babelrc'),
          },
        },
        "styled-jsx-css-loader",
      ]
}
[...]

// navigation.js
import styles from "./navigation.css";

export default () => {
  return (
    <div>
      <Button href="/">Home</Button>
      <Button href="/about">About</Button>
      <Button route="product" params={{slug: "plant"}}>Plant</Button>
      <Button route="product" params={{slug: "tree"}}>Tree</Button>
      <style jsx>{styles}</style>
    </div>
  );

};
```

Do you experience something differnt? Or is that an implication of the emit-file-loader and therefore a technical limitation or is there anything that we can do on our end?

Any kind of feedback is appreciated :-)

Cheers,
Tom

**Comment by tom2strobl** [comment]
It had nothing to do with the repo, was just a coincidence. Instead it was an old getinitialprops on the _document which caused the server not to render the styles... Sorry.

**Comment by coox** [comment]
Hey @tom2strobl — Sorry for not having gotten back to you earlier. I wanted to be able to reproduce your issue first, which I was puzzled about, since server-side rendering should normally pre-render styled-jsx-generated styles in the `<head>` of your document. I’m glad you had it sorted out :-)
