### ISSUE TITLE
Support scss syntax

### ISSUE THREAD

**Issue by arefaslani** [coox/styled-jsx-css-loader#6]
It would be nice to add support for scss. So that I can import my other scss files. for example:
```scss
// style.scss
@import "./variables.scss"
```

```jsx
// my component
// ...
import styles from './style.scss'
// ...
```

**Comment by P233** [comment]
I replaced the `/\.css$/` to `/\.scss$/`, and it works fine for the scss syntax. But I got another issue about nextjs doesn't hot reload when the `@import`ed scss file updated. Does anyone have a clue to solve this? thanks

**Comment by connor-baer** [comment]
@arefaslani You can get it to work with SCSS by adding the appropriate loaders before the `styled-jsx-css-loader`. Here's my config: 

```js
module.exports = {
  webpack(config, { dev }) {
    config.module.rules.push({
      test: /\.scss$/,
      use: [
        {
          loader: 'emit-file-loader',
          options: {
            name: 'dist/[path][name].[ext].js'
          }
        },
        {
          loader: 'babel-loader',
          options: {
            babelrc: false,
            extends: path.resolve(__dirname, './.babelrc')
          }
        },
        'styled-jsx-css-loader',
        { loader: 'postcss-loader', options: { sourceMap: dev } },
        {
          loader: 'sass-loader',
          options: {
            sourceMap: dev,
            includePaths: [normalizePath].concat(neatPath).concat(bourbonPath)
          }
        }
      ]
    });
    return config;
  }
};
```

**Comment by arefaslani** [comment]
@connor-baer is hot reloading and importing scss files enabled that way?

**Comment by connor-baer** [comment]
@arefaslani You can definitely import (other) SCSS files this way. I briefly tested hot reloading, doesn't seem to work. :(

Update: **HMR works! 🎉**

**Comment by connor-baer** [comment]
Don't take that too seriously though. I'm in the process of moving a large code base to Next.js and hot reloading doesn't work at all at the moment. 😬

**Comment by connor-baer** [comment]
@arefaslani I finally got HMR to work and I stand corrected — the styles reload as well! 🎉

@P233 My approach also reloads when `@import`ed files are changed.

**Comment by jbsmith731** [comment]
@connor-baer did you change the config you shared above or was it something else?

**Comment by connor-baer** [comment]
My config is still the same.
I am using a custom express server and one of the middlewares was interfering. It redirects all urls to their canonical version with a trailing slash. This prevented the HMR path (`_next/webpack-hmr`) from being accessible.
