### ISSUE TITLE
Prepare for styled-jsx v3

### ISSUE THREAD

**Issue by giuseppeg** [coox/styled-jsx-css-loader#7]
Hi Eric! I will release styled-jsx v3 soon and I wanted to know if you would be interested in adapting this loader to support the new features. You can read about what is changing here https://github.com/zeit/styled-jsx/pull/422 

tl;dr basically styled-jsx will produce only scoped styles when you tag the string with `css`. To get global or (resolved) styles you'd need to tag strings with `css.global` or `css.resolve`. I think that we could make your plugin accept an option for the type of compilation to do. The default would be `scoped`.

The loader should output 

```js
const type = options.type === 'global' || options.type === 'resolve' ? `.${options.type}` : '';
"import css from 'styled-jsx/css';\n\nexport default css"+type+"`" + escapedContent + "`;";
```

Let me know if you are willing to make this change otherwise I'll go ahead and fork :)

**Comment by coox** [comment]
Hello @giuseppeg —

Thanks for opening this issue, and nice feature!

Yes, I will take this opportunity to adapt the loader for styled-jsx v3. This will also be an opportunity to clarify some docs, upgrade examples, and fix a few quirks I’ve noticed. I should be able to work on this within a few days… I’ll keep you posted right here.

**Comment by paschaldev** [comment]
@coox Any update on this

**Comment by MosheBaram** [comment]
@coox Any update? It has been quite a while now.

**Comment by giuseppeg** [comment]
woops, I forgot to mention that I ended up writing a similar loader and included it in styled-jsx v3 See https://github.com/zeit/styled-jsx#styles-in-regular-css-files

**Comment by coox** [comment]
@paschaldev @MosheBaram — 

styled-jsx v3 came out [with its own webpack loader](https://github.com/zeit/styled-jsx#styles-in-regular-css-files). If you want to load external CSS files, `styled-jsx/webpack` is essentially a drop-in replacement.

[styled-jsx-css-loader](https://github.com/coox/styled-jsx-css-loader) is now only useful if you must use styled-jsx v2, I’ll mark it as deprecated quite soon.
